vroom_car_rentals/vroom/urls.py
from django.urls import path
from . import views

app_name = 'vroom'

urlpatterns = [
    path('', views.index, name='index'),
    path('cars/', views.cars, name='cars'),
    path('log-in/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('stores/', views.stores, name='stores'),
    path('store-history/', views.storehistory, name='storehistory'),
    path('customers/', views.viewcustomers, name='viewcustomers'),
    path('analytics/', views.analytics, name='analytics')

]

vroom_car_rentals/vroom_car_rentals/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('vroom.urls')),
    path('admin/', admin.site.urls),
]

vroom_car_rentals/vroom/models.py
from django.db import models

class Store(models.Model):
    store_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)

class Role(models.Model):
    role_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)

class Car(models.Model):
    car_id = models.AutoField(primary_key=True)
    make_name = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    series = models.CharField(max_length=100)
    seriesYear = models.IntegerField()
    price_new = models.IntegerField()
    engine_size = models.CharField(max_length=100)
    fuel_system = models.CharField(max_length=100)
    tank_capacity = models.CharField(max_length=100)
    power = models.CharField(max_length=100)
    seating_capacity = models.IntegerField()
    standard_transmission = models.CharField(max_length=100)
    body_type = models.CharField(max_length=100)
    drive = models.CharField(max_length=100)
    wheelbase = models.CharField(max_length=100)

class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20, null=True)
    address = models.CharField(max_length=100, null=True)
    birthday = models.DateField(null = True)
    occupation = models.CharField(max_length=10, null=True)
    gender = models.CharField(max_length=1, null=True)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    password = models.CharField(max_length=100)
    salt = models.CharField(max_length=100)

class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    create_date = models.DateField()
    pickup_date = models.DateField()
    pickup_store = models.ForeignKey(Store, related_name='pickup_store', on_delete=models.CASCADE)
    return_date = models.DateField()
    return_store = models.ForeignKey(Store, related_name='return_store', on_delete=models.CASCADE)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

vroom_car_rentals/vroom/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .functions import *
import re
import calendar

def index(request):
    return render(request, 'vroom/index.html')

def cars(request):
    cars = get_all_cars() # Retrieve all the cars and the relevant information (from functions.py)
    stores = Store.objects.values('name') # Retrieves the names of the stores
    make_name = Car.objects.values('make_name').order_by('make_name').distinct() # Retrieves all makes of cars from the database
    seriesYear = Car.objects.values('seriesYear').order_by('seriesYear').distinct() # Retrieves the years stored in the database
    fuel_system = Car.objects.values('fuel_system').order_by('fuel_system').distinct() # Retrieves the fuel systems stored in the database
    body_type = Car.objects.values('body_type').order_by('body_type').distinct() # Retrieves the different types of cars stored in the database
    seating_capacity = Car.objects.values('seating_capacity').order_by('seating_capacity').distinct() # Retrieves the seating_capacity stored in the database	
    drive = Car.objects.values('drive').order_by('drive').distinct() # Retrieves the drive types stored in the database
    filter = '' # Declare a string that'll be used for getting results by name
    context = {'list_of_cars': cars, 'filter': filter, 'stores': stores, 'make_name': make_name, 'seriesYear': seriesYear, 'fuel_system': fuel_system,
               'body_type': body_type, 'seating_capacity': seating_capacity, 'drive': drive, 'price_min': request.GET.get('price-min'), 'price_max': request.GET.get('price-max')} # Create a context dictionary that contains the retrieved cars and information used in filters

    if 'search' in request.GET and not 'clear' in request.GET: # The user has entered the cars page via the home site search or the cars page search bar
        filter = '%s' % request.GET.get('search') # Prepare a filter to apply to the cars retrieved
        context['filter'] = filter # Update the context
        filter_names = list() # Create a list to store the currently selected filter values
        cars = cars.filter(car__price_new__range=(request.GET.get('price-min'), request.GET.get('price-max')))	

        if 'sort' in request.GET: # Sort the Results by Tank Capacity and determine sort input
            if request.GET.get('sort') == "Car_TankCapacity":
                context['sort'] = 'tank_high' # Set field to sort by to tank_high
                filter_names.append(request.GET.get('tank_high')) # Remember which drop-down item was used
                if request.GET.get('tank_high') == "high": # Sort By highest to lowest
                    cars = cars.extra({'tank_capacity': "tank_capacity + 0"}).order_by('-tank_capacity')
                else: # Sort By Lowest to highest
                    cars = cars.extra({'tank_capacity': "tank_capacity + 0"}).order_by('tank_capacity')

            elif request.GET.get('sort') == "Price_New": # Sort the Results by Price and determine sort input
                context['sort'] = 'price_high' # Set field to sort by to price_high
                filter_names.append(request.GET.get('price_high'))
                if request.GET.get('price_high') == "high": # Sort from highest to lowest
                    cars = cars.order_by('-car__price_new')
                else: # Sort from lowest to highest
                    cars = cars.order_by('car__price_new')

            elif request.GET.get('sort') == "Power": # Sort the Results by Power and determine sort input
                context['sort'] = 'power_high' # Set field to sort by to power_high
                filter_names.append(request.GET.get('power_high'))
                if request.GET.get('power_high') == "high": # Sort from highest to lowest
                    cars = cars.extra({'power': "power + 0"}).order_by('-power')
                else: # Sort from lowest to highest
                    cars = cars.extra({'power': "power + 0"}).order_by('power')

        # Iterates through an array of names and parameters to apply filters.
        filters = [['store', 'return_store__name'], ['make_name', 'car__make_name'], ['year', 'car__seriesYear'],
                      ['fuel_system', 'car__fuel_system'], ['body_type', 'car__body_type'], ['drive', 'car__drive'],
                      ['seating_capacity', 'car__seating_capacity']]
        for name, parameter in filters:
            if name in request.GET and request.GET.get(name) != "":
                cars = cars.filter(**{parameter: request.GET.get(name)}) # Set the parameter to be whatever value is retrieved
                if name not in ('year', 'seating_capacity'):
                    filter_names.append(request.GET.get(name))
                else:
                    filter_names.append(int(request.GET.get(name)))

        if len(filter_names) > 0:
            context['filter_names'] = filter_names

    cars = cars.filter(car__model__icontains=filter) # Filter the cars so that only ones with a similar model name appear
    context['list_of_cars'] = cars # Update the context with new results

    return render(request, 'vroom/cars.html', context)

def viewcustomers(request):
    users = get_all_customers() # Retrieve all the user information, from functions.py

    if 'search' in request.GET:
        filter = '%s' % request.GET.get('search') # Prepare a filter to apply to the users retrieved
    else:
        filter = ''

    users = users.filter(name__icontains=filter) # Filter the users so that only ones with a similar model name appear
    context = {'list_of_users': users, 'filter': filter}

    return render(request, 'vroom/viewcustomers.html', context)

def login(request):
    if 'id' in request.POST and 'password' in request.POST: # The user has entered the login site by entering their login details
        id = request.POST.get('id') # Get the input id
        password = request.POST.get('password') # Get the input password (from login form)

        if authenticate_user(id, password): # Check that the user exists in the table
            user_information = get_user_info(id, password) # Get the name and access of the user
            request.session['username'] = user_information['username'] # Create a session variable for their name
            request.session['access'] = user_information['access'] # Create a session variable for their access
            request.session['id'] = id # Create a session variable for their id

            return redirect('vroom:index') # Redirect the user back to the home page

        context = {'id': id, 'password': password} # The users information was not found in the database
        return render(request, 'vroom/log-in.html', context) # Render the login page again (will now have their details auto-filled and a message)

    return render(request, 'vroom/log-in.html') # Render the login page for the first time

def logout(request):
    if request.session['username'] and request.session['access']: # Make sure the session variables are created
        del request.session['username'] # Remove the session variable
        del request.session['access'] # Remove the session variable

        request.session.modified = True # Ensure django knows the session variables were modified

    return redirect('vroom:index') # Redriect the user to the home page

def stores(request):
    stores = Store.objects.values('name', 'store_id', 'address', 'phone')
    context = {'stores': stores}
    return render(request, 'vroom/stores.html', context)

def storehistory(request):
    orders = get_all_orders() # Retrive all the order information (from functions.py)
    stores = get_all_stores() # Retrieve all the store information (from functions.py)
    try: # A failure occurs when no one is logged in (accessing via search bar)
        context = {'list_of_stores': stores}
        if request.session['access'] == "CUSTOMER": # This is the line that fails
            orders = orders.filter(customer__user_id=request.session['id'])
        else:
            users = get_all_customers().filter(role=1).order_by('name')
            context['list_of_users'] = users
        context['table_data'] = {'Orders': orders}

        if not 'clear' in request.GET:
            if 'user' in request.GET:
                orders = orders.filter(customer__name=request.GET.get('user'))
                context['table_data'] = {'Orders': orders}
                context['selected_user_name'] = request.GET.get('user')

            if 'store' in request.GET:
                selected_store_id = int(request.GET.get('store')) # Retrieve the selected store id from the html form
                pickup_stores = orders.filter(pickup_store=selected_store_id)
                return_stores = orders.filter(return_store=selected_store_id)
                selected_store_name = stores.get(store_id=selected_store_id).name # Retrieve the name that belongs to the ID
                pickup_order_table_name = 'Pickup Orders:'
                return_order_table_name = 'Return Orders:'

                if len(pickup_stores) == 0: # If there aren't any values in pickup_stores and/or return_stores, set the respective title to have 'No' at the begining
                    pickup_order_table_name = 'No Pickup Orders'
                if len(return_stores) == 0:
                    return_order_table_name = 'No Return Orders'

                context['table_data'] = {pickup_order_table_name: pickup_stores, return_order_table_name: return_stores} # Used for simplifying the code in storehistory.html
                context['selected_store_name'] = selected_store_name
                context['selected_store_id'] = selected_store_id

    except KeyError: # Prevent a user that isn't logged in from viewing anything upon failure
        context = {'list_of_stores': stores, 'table_data': {"You don't have permission to view this page.": None}}

vroom_car_rentals/vroom/templates/vroom/base.html
<!DOCTYPE html>
<html>
{% include 'vroom/head.html' %}
<body>
    {% include 'vroom/header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'vroom/footer.html' %}
</body>
</html>

vroom_car_rentals/vroom/templates/vroom/cars.html
{% extends "vroom/base.html" %}

{% block content %}
{% load static %}

<script>
    function update(element){
        var minPrice = document.getElementById('price-min').value;
		var maxPrice = document.getElementById('price-max').value;
		document.getElementById('minSpan').innerHTML = "$" + minPrice;
        document.getElementById('maxSpan').innerHTML = "$" + maxPrice;
        document.getElementById('price-min').max = maxPrice;
        document.getElementById('price-max').min = minPrice;
	}
	
	function hide_drop(value){
		document.getElementById("tank_high").style.visibility = "hidden";
		document.getElementById("price_high").style.visibility = "hidden";
		document.getElementById("power_high").style.visibility = "hidden";
		
		document.getElementById("tank_high").disabled = true;
		document.getElementById("price_high").disabled = true;
		document.getElementById("power_high").disabled = true;

		if (value != null) {
            document.getElementById(value + "_radio").checked = true;
            document.getElementById(value).style.visibility = "visible";
		    document.getElementById(value).disabled = false;
        }
	}
</script>

<!--The main content of the webpage-->
<main>
    <!--First section of the main content. A banner which usually displays the most important information-->
    <section class="main-cont">
        <h2 class="search-heading">Search</h2>
        <form id="cars-form" name="searchForm" method="GET" action="{% url 'vroom:cars' %}">
            <div id="main-search">
                {% if filter == '' %}
                <input type="search" name="search" id="search-text" placeholder="Enter a name" />
                {% else %}
                <input type="search" name="search" id="search-text" placeholder="Enter a name" value={{ filter }} />
                {% endif %}
                {% if filter_names %}
                <input type="submit" name="clear" value="Clear Filter"> <!--Clears the store filter-->
                {% endif %}
                <input type="submit" id="search-btn" value="Search"/>
            </div>
			
			<div id="sortBy">
				<strong>Sort By:</strong><br>
				<input type="radio" name="sort" value="" onclick="hide_drop(null);" checked> Default<br>
				<input type="radio" name="sort" id="tank_high_radio" value="Car_TankCapacity" onclick="hide_drop('tank_high');"> Tank Capacity
                
                <select name="tank_high" id="tank_high">
                    {% if "low" in filter_names %}
                    <option value="high">Highest to Lowest</option>
                    <option value="low" selected>Lowest to Highest</option>
                    {% else %}
                    <option value="high" selected>Highest to Lowest</option>
                    <option value="low">Lowest to Highest</option>
                    {% endif %}
				</select>
				<br>
				
				<input type="radio" name="sort" id="price_high_radio" value="Price_New" onclick="hide_drop('price_high');"> Price
				<select name="price_high" id="price_high">
                    {% if "low" in filter_names %}
                    <option value="high">Highest to Lowest</option>
                    <option value="low" selected>Lowest to Highest</option>
                    {% else %}
                    <option value="high" selected>Highest to Lowest</option>
                    <option value="low">Lowest to Highest</option>
                    {% endif %}
				</select>
				<br>
				
				<input type="radio" name="sort" id="power_high_radio" value="Power" onclick="hide_drop('power_high');"> Power
				<select name="power_high" id="power_high">
                    {% if "low" in filter_names %}
                    <option value="high">Highest to Lowest</option>
                    <option value="low" selected>Lowest to Highest</option>
                    {% else %}
                    <option value="high" selected>Highest to Lowest</option>
                    <option value="low">Lowest to Highest</option>
                    {% endif %}
				</select>
                <br>
			</div>
			<script type="text/javascript"> hide_drop('{{sort}}');</script>
			
            <div id="filters">
			<strong>Filter By:</strong> <br>
                <select name="store">
                    <option value="">Store:</option>
                    {% for item in stores %}
                    {% if not item.name in filter_names %}
                    <option value="{{ item.name }}">{{ item.name }}</option>
                    {% else %}
                    <option value="{{ item.name }}" selected>{{ item.name }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <select name="make_name">
                    <option value="">Make:</option>
                    {% for item in make_name %}
                    {% if not item.make_name in filter_names %}
                    <option value="{{ item.make_name }}">{{ item.make_name }}</option>
                    {% else %}
                    <option value="{{ item.make_name }}" selected>{{ item.make_name }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <select name="year">
                    <option value="">Year:</option>
                    {% for item in seriesYear %}
                    {% if not item.seriesYear in filter_names %}
                    <option value={{ item.seriesYear }}>{{ item.seriesYear }}</option>
                    {% else %}
                    <option value={{ item.seriesYear }} selected>{{ item.seriesYear }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <select name="fuel_system">
                    <option value="">Fuel System:</option>
                    {% for item in fuel_system %}
                    {% if not item.fuel_system in filter_names %}
                    <option value="{{ item.fuel_system }}">{{ item.fuel_system }}</option>
                    {% else %}
                    <option value="{{ item.fuel_system }}" selected>{{ item.fuel_system }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <select name="body_type">
                    <option value="">Body Type:</option>
                    {% for item in body_type %}
                    {% if not item.body_type in filter_names %}
                    <option value="{{ item.body_type }}">{{ item.body_type }}</option>
                    {% else %}
                    <option value="{{ item.body_type }}" selected>{{ item.body_type }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <select name="seating_capacity">
                    <option value="">Seating:</option>
                    {% for item in seating_capacity %}
                    {% if not item.seating_capacity in filter_names %}
                    <option value="{{ item.seating_capacity }}">{{ item.seating_capacity }}</option>
                    {% else %}
                    <option value="{{ item.seating_capacity }}" selected>{{ item.seating_capacity }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <select name="drive">
                    <option value="">Drive:</option>
                    {% for item in drive %}
                    {% if not item.drive in filter_names %}
                    <option value={{ item.drive }}>{{ item.drive }}</option>
                    {% else %}
                    <option value={{ item.drive }} selected>{{ item.drive }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="rangeslider">
                <label for="price-min">Min:</label>
                {% if price_min %}
                <input type="range" name="price-min" id="price-min" value="{{ price_min }}" min="0" step= '1000' max='250000' oninput="update('price-min');"><span id="minSpan">${{ price_min }}</span>
                <label for="price-max">Max:</label>
                <input type="range" name="price-max" id="price-max" value="{{ price_max }}" min="0" max="250000" step= '1000' oninput="update('price-max');"><span id="maxSpan">${{ price_max }}</span>
                {% else %}
                <input type="range" name="price-min" id="price-min" value="0" min="0" step= '1000' max='250000' oninput="update('price-min');"><span id="minSpan">$0</span>
                <label for="price-max">Max:</label>
                <input type="range" name="price-max" id="price-max" value="250000" min="0" max="250000" step= '1000' oninput="update('price-max');"><span id="maxSpan">$250000</span>
                {% endif %}
            </div>
        </form>
    </section>
    <!--Second section which contains the less important information but is still useful-->
    <div class="sub-cont results">
        <h3>Results</h3>
        <!--List of search results-->
        {% if list_of_cars %}
        <table>
            <tbody>
                <tr>
                    {% if request.session.access == 'GENERAL_STAFF' %}
                    <th>ID</th>
                    {% endif %}
                    <th>Make</th>
                    <th>Model</th>
                    <th>Series</th>
                    <th>Year</th>
                    <th>Price</th>
                    <th>Store</th>
                    <th>Engine</th>
                    <th>Fuel System</th>
                    <th>Tank</th>
                    <th>Power</th>
                    <th>Seats</th>
                    <th>Transmission</th>
                    <th>Type</th>
                    <th>Drive</th>
                    <th>WheelBase</th>
                </tr>
                {% for item in list_of_cars %}
                <tr>
                    {% if request.session.access == 'GENERAL_STAFF' %}
                    <td>{{ item.car.car_id }}</td>
                    {% endif %}
                    <td>{{ item.car.make_name }}</td>
                    <td>{{ item.car.model }}</td>
                    <td>{{ item.car.series }}</td>
                    <td>{{ item.car.seriesYear }}</td>
                    <td>{{ item.car.price_new }}</td>
                    <td>{{ item.return_store.name }}</td>
                    <td>{{ item.car.engine_size }}</td>
                    <td>{{ item.car.fuel_system }}</td>
                    <td>{{ item.car.tank_capacity }}</td>
                    <td>{{ item.car.power }}</td>
                    <td>{{ item.car.seating_capacity }}</td>
                    <td>{{ item.car.standard_transmission }}</td>
                    <td>{{ item.car.body_type }}</td>
                    <td>{{ item.car.drive }}</td>
                    <td>{{ item.car.wheelbase }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>Oops. We couldn't find any cars matching your search</p>
        {% endif %}
    </div>
</main>
{% endblock %}

vroom_car_rentals/vroom/templates/vroom/footer.html
<!--The footer of the webpage (contains the name and year of the website and the creator of the website)-->
    <footer>
        <p>&copy; Vroom Car Rentals 2018. Car Rental Compnany</p>
    </footer>

vroom_car_rentals/vroom/templates/vroom/header.html
<!--The header of the document (main bar up the top) contains the navigation and the name of the website-->
    <header>
        <!--The name of the website (also links to the home page)-->
        <h1><a href="{% url 'vroom:index' %}">Vroom Car Rentals</a></h1>
        <!--Navigation bar (contains a list of navigation elements that take you to the coresponding page)-->
        <nav>
            <ul>
                <li><a href="{% url 'vroom:cars' %}">Cars</a></li>
                <li><a href="{% url 'vroom:stores' %}">Stores</a></li>
                {% if request.session.username != None %}
                {% if request.session.access == "GENERAL_STAFF" %}
                <li><a href="{% url 'vroom:viewcustomers' %}">Customers</a></li>
                <li><a href="{% url 'vroom:analytics' %}">Analytics</a></li>
                {% endif %}
                <li><a href="{% url 'vroom:storehistory' %}">Rental History</a></li>
                <li class="sign-up-btn"><a href="{% url 'vroom:logout' %}">Log Out</a></li>
                <b>Logged in as: {{request.session.username}}</b>
                {% else %} <!--Only shows the login button when no one is logged in-->
                <li><a href="{% url 'vroom:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

vroom_car_rentals/vroom/templates/vroom/index.html
{% extends "vroom/base.html" %}

{% block content %}
{% load static %}
<!--The main content of the webpage-->
<main>
    <!--First section of the main content. A banner which usually displays the most important information-->
    <section class="main-cont">
        <img src="{% static 'vroom/images/logo-white.png' %}" alt="" />
        <h2>Welcome to Vroom Car Rentals</h2>
        <p>Vroom Car Rentals is the best place to go if you're looking to rent a car and have a wide variety to choose.</p>
        <form id="index-form" name="search" method="GET" action="{% url 'vroom:cars' %}">
            <input type="search" name="search" placeholder="Search for a car..." />
            <input type="submit" value="Get Started" />
        </form>
    </section>
    <!--Second section which contains the less important information but is still useful-->
    <div class="sub-cont">
        <article>
            <a href="{% url 'vroom:cars' %}">
                <img src="{% static 'vroom/images/search-purple.png' %}" alt="" />
                <h3 style="color: var(--purple)">Find Cars</h3>
            </a>
            <p>Search over 500 cars filtering by name, price, seats and much more.</p>
        </article>
        <article>
            {% if request.session.username != None %} <!--Only link when a user is logged in-->
            <a href="{% url 'vroom:storehistory' %}"> <!--Go to the rentalhistory page-->
            {% endif %}
                <img src="{% static 'vroom/images/history-blue.png' %}" alt="" />
                <h3 style="color: var(--blue)">Rental History</h3>
            </a>
            <p>Log in to be able to view your history of rentals with us.<p>
        </article>
        <article>
            <a href="#">
                <img src="{% static 'vroom/images/sign-up-orange.png' %}" alt="" />
                <h3 style="color: var(--orange)">Sign Up</h3>
            </a>
            <p>Don't have an account? Sign up for one now. It's free!</p>
        </article>
    </div>
</main>
{% endblock %}

vroom_car_rentals/vroom/templates/vroom/log-in.html
{% extends "vroom/base.html" %}

{% block content %}
{% load static %}

<!--The main content of the webpage-->
    <main>
        <!--Log In form-->
        <form name="login" id="login" class="account-form" method="POST" action="{% url 'vroom:login' %}">
            <fieldset>
                <legend>Log In</legend>
                <p>Hi! Welcome to <span class="blue">Vroom Car Rentals.</span></p>
                <p>To access more features, please Log In.</p>
                {% csrf_token %}
                {% if id and password %}
                <p class="bad-login">Error: ID/Password was incorrect</p>
                {% endif %}
                <input type="text" name="id" placeholder="User ID" pattern="[0-9]*" required value="{{ id }}" />
                <input type="password" name="password" placeholder="Password" pattern="[^\n ]{5,}" title="Password should be 5 or more characters" required value="{{ password }}" />
                <input type="submit" value="Log In" />
            </fieldset>
        </form>
    </main>
{% endblock %}

vroom_car_rentals/vroom/templates/vroom/viewcustomers.html
{% extends "vroom/base.html" %}

{% block content %}
{% load static %}
<!-- Main content of the webpage -->
<main>
    <!--First section of the main content. A banner which usually displays the most important information-->
    <section class="main-cont">
        <h2 class="search-heading">Search</h2>
        <form id="user-form" name="searchForm" method="GET" action="{% url 'vroom:viewcustomers' %}">
            <div id="main-search">
                {% if filter == '' %}
                <input type="search" name="search" id="search-text" placeholder="Enter a name" />
                {% else %}
                <input type="search" name="search" id="search-text" placeholder="Enter a name" value={{ filter }} />
                {% endif %}
                <input type="submit" id="search-btn" value="Search" />
            </div>
        </form>
    </section>
    <!-- this here is for the return of the search -->
    <div class="sub-cont results">
        {% if request.session.access == 'GENERAL_STAFF' %} <!-- Check if the user is a member of staff -->
        <h3>Results</h3>
        <!--List of search results-->
        {% if list_of_users %}
        <table>
            <tbody>
                <tr>
                    <th>User ID</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>Birthday</th>
                </tr>
                {% for item in list_of_users %}
                <tr>
                    <td>{{item.user_id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.phone}}</td>
                    <td>{{item.address}}</td>
                    <td>{{item.birthday}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>Oops. We couldn't find any customers matching your search</p>
        {% endif %}
        {% else %}
        <h2>Staff Only Information - Please Login to Continue</h2>
        {% endif %}
    </div>
</main>
{% endblock %}